# Generated by Django 4.2.6 on 2023-10-23 11:45

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='volume',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=16),
        ),
    ]
