# Generated by Django 4.2.6 on 2023-10-23 11:45

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='equity_capital',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=16),
        ),
        migrations.AlterField(
            model_name='broker',
            name='trading_turnover',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='share_capital',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=16),
        ),
    ]
