# Generated by Django 4.2.6 on 2023-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
